/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    projects: Project;
    comics: Comic;
    chapters: Chapter;
    characters: Character;
    'project-updates': ProjectUpdate;
    'tracker-items': TrackerItem;
    galleries: Gallery;
    'archive-items': ArchiveItem;
    media: Media;
    tags: Tag;
    categories: Category;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    comics: ComicsSelect<false> | ComicsSelect<true>;
    chapters: ChaptersSelect<false> | ChaptersSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    'project-updates': ProjectUpdatesSelect<false> | ProjectUpdatesSelect<true>;
    'tracker-items': TrackerItemsSelect<false> | TrackerItemsSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    'archive-items': ArchiveItemsSelect<false> | ArchiveItemsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  projectCode: string;
  yearsActive?: string | null;
  status: string;
  productionPhase?: string | null;
  summary?: string | null;
  description?: string | null;
  writing?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  galleries?: (number | Gallery)[] | null;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  /**
   * Optional display label, preserved from the prototype.
   */
  categoryLabel?: string | null;
  placeholderArt?: ('art-a' | 'art-b' | 'art-c') | null;
  contentUpdated?: string | null;
  /**
   * Metadata visibility only. Does not grant access to writing or files. Locked listings are not exposed in this foundation.
   */
  listingVisibility: 'public' | 'hidden';
  accessLevel: 'public' | 'patron';
  /**
   * Optional safe teaser for future directory listings. Never put restricted writing here.
   */
  listingSummary?: string | null;
  legacyKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Files become public only when published, PUBLIC, and attached to published public content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  uploadKey?: string | null;
  project?: (number | null) | Project;
  /**
   * Metadata visibility only. Does not grant access to writing or files. Locked listings are not exposed in this foundation.
   */
  listingVisibility: 'public' | 'hidden';
  accessLevel: 'public' | 'patron';
  /**
   * Optional safe teaser for future directory listings. Never put restricted writing here.
   */
  listingSummary?: string | null;
  legacyKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title: string;
  slug: string;
  project?: (number | null) | Project;
  description?: string | null;
  /**
   * Add existing uploads or upload a file in each row. Row order is display order.
   */
  images?:
    | {
        media: number | Media;
        caption?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?: (number | Tag)[] | null;
  /**
   * Metadata visibility only. Does not grant access to writing or files. Locked listings are not exposed in this foundation.
   */
  listingVisibility: 'public' | 'hidden';
  accessLevel: 'public' | 'patron';
  /**
   * Optional safe teaser for future directory listings. Never put restricted writing here.
   */
  listingSummary?: string | null;
  legacyKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comics".
 */
export interface Comic {
  id: number;
  title: string;
  slug: string;
  project: number | Project;
  description?: string | null;
  cover?: (number | null) | Media;
  /**
   * Metadata visibility only. Does not grant access to writing or files. Locked listings are not exposed in this foundation.
   */
  listingVisibility: 'public' | 'hidden';
  accessLevel: 'public' | 'patron';
  /**
   * Optional safe teaser for future directory listings. Never put restricted writing here.
   */
  listingSummary?: string | null;
  legacyKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters".
 */
export interface Chapter {
  id: number;
  title: string;
  slug: string;
  comic: number | Comic;
  chapterNumber: number;
  description?: string | null;
  /**
   * Add existing uploads or upload a file in each row. Row order is display order.
   */
  pages: {
    media: number | Media;
    caption?: string | null;
    alt?: string | null;
    id?: string | null;
  }[];
  routeKey?: string | null;
  /**
   * Metadata visibility only. Does not grant access to writing or files. Locked listings are not exposed in this foundation.
   */
  listingVisibility: 'public' | 'hidden';
  accessLevel: 'public' | 'patron';
  /**
   * Optional safe teaser for future directory listings. Never put restricted writing here.
   */
  listingSummary?: string | null;
  legacyKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  name: string;
  slug: string;
  project: number | Project;
  role?: string | null;
  description?: string | null;
  writing?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Add existing uploads or upload a file in each row. Row order is display order.
   */
  images?:
    | {
        media: number | Media;
        caption?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedChapters?: (number | Chapter)[] | null;
  tags?: (number | Tag)[] | null;
  /**
   * Metadata visibility only. Does not grant access to writing or files. Locked listings are not exposed in this foundation.
   */
  listingVisibility: 'public' | 'hidden';
  accessLevel: 'public' | 'patron';
  /**
   * Optional safe teaser for future directory listings. Never put restricted writing here.
   */
  listingSummary?: string | null;
  legacyKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-updates".
 */
export interface ProjectUpdate {
  id: number;
  title: string;
  project: number | Project;
  date: string;
  writing?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description?: string | null;
  /**
   * Add existing uploads or upload a file in each row. Row order is display order.
   */
  images?:
    | {
        media: number | Media;
        caption?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  milestone?: (number | null) | TrackerItem;
  statusInfo?: string | null;
  /**
   * Metadata visibility only. Does not grant access to writing or files. Locked listings are not exposed in this foundation.
   */
  listingVisibility: 'public' | 'hidden';
  accessLevel: 'public' | 'patron';
  /**
   * Optional safe teaser for future directory listings. Never put restricted writing here.
   */
  listingSummary?: string | null;
  legacyKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracker-items".
 */
export interface TrackerItem {
  id: number;
  title: string;
  project: number | Project;
  kind: 'phase' | 'milestone';
  percentage?: number | null;
  order: number;
  status?: string | null;
  lastUpdated?: string | null;
  /**
   * Metadata visibility only. Does not grant access to writing or files. Locked listings are not exposed in this foundation.
   */
  listingVisibility: 'public' | 'hidden';
  accessLevel: 'public' | 'patron';
  /**
   * Optional safe teaser for future directory listings. Never put restricted writing here.
   */
  listingSummary?: string | null;
  legacyKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archive-items".
 */
export interface ArchiveItem {
  id: number;
  title: string;
  slug: string;
  project?: (number | null) | Project;
  category?: (number | null) | Category;
  tags?: (number | Tag)[] | null;
  description?: string | null;
  date?: string | null;
  /**
   * Add existing uploads or upload a file in each row. Row order is display order.
   */
  files?:
    | {
        media: number | Media;
        caption?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Metadata visibility only. Does not grant access to writing or files. Locked listings are not exposed in this foundation.
   */
  listingVisibility: 'public' | 'hidden';
  accessLevel: 'public' | 'patron';
  /**
   * Optional safe teaser for future directory listings. Never put restricted writing here.
   */
  listingSummary?: string | null;
  legacyKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'comics';
        value: number | Comic;
      } | null)
    | ({
        relationTo: 'chapters';
        value: number | Chapter;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'project-updates';
        value: number | ProjectUpdate;
      } | null)
    | ({
        relationTo: 'tracker-items';
        value: number | TrackerItem;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'archive-items';
        value: number | ArchiveItem;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  projectCode?: T;
  yearsActive?: T;
  status?: T;
  productionPhase?: T;
  summary?: T;
  description?: T;
  writing?: T;
  heroImage?: T;
  galleries?: T;
  categories?: T;
  tags?: T;
  categoryLabel?: T;
  placeholderArt?: T;
  contentUpdated?: T;
  listingVisibility?: T;
  accessLevel?: T;
  listingSummary?: T;
  legacyKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comics_select".
 */
export interface ComicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  project?: T;
  description?: T;
  cover?: T;
  listingVisibility?: T;
  accessLevel?: T;
  listingSummary?: T;
  legacyKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters_select".
 */
export interface ChaptersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  comic?: T;
  chapterNumber?: T;
  description?: T;
  pages?:
    | T
    | {
        media?: T;
        caption?: T;
        alt?: T;
        id?: T;
      };
  routeKey?: T;
  listingVisibility?: T;
  accessLevel?: T;
  listingSummary?: T;
  legacyKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  project?: T;
  role?: T;
  description?: T;
  writing?: T;
  images?:
    | T
    | {
        media?: T;
        caption?: T;
        alt?: T;
        id?: T;
      };
  relatedChapters?: T;
  tags?: T;
  listingVisibility?: T;
  accessLevel?: T;
  listingSummary?: T;
  legacyKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-updates_select".
 */
export interface ProjectUpdatesSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  date?: T;
  writing?: T;
  description?: T;
  images?:
    | T
    | {
        media?: T;
        caption?: T;
        alt?: T;
        id?: T;
      };
  milestone?: T;
  statusInfo?: T;
  listingVisibility?: T;
  accessLevel?: T;
  listingSummary?: T;
  legacyKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracker-items_select".
 */
export interface TrackerItemsSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  kind?: T;
  percentage?: T;
  order?: T;
  status?: T;
  lastUpdated?: T;
  listingVisibility?: T;
  accessLevel?: T;
  listingSummary?: T;
  legacyKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  project?: T;
  description?: T;
  images?:
    | T
    | {
        media?: T;
        caption?: T;
        alt?: T;
        id?: T;
      };
  tags?: T;
  listingVisibility?: T;
  accessLevel?: T;
  listingSummary?: T;
  legacyKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archive-items_select".
 */
export interface ArchiveItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  project?: T;
  category?: T;
  tags?: T;
  description?: T;
  date?: T;
  files?:
    | T
    | {
        media?: T;
        caption?: T;
        alt?: T;
        id?: T;
      };
  listingVisibility?: T;
  accessLevel?: T;
  listingSummary?: T;
  legacyKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  uploadKey?: T;
  project?: T;
  listingVisibility?: T;
  accessLevel?: T;
  listingSummary?: T;
  legacyKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}